[package]
name = "advent23"
version = "0.1.0"
edition = "2021"

[dependencies]
fancy-regex = { version = "0.12.0", features = ["perf-backtrack"] }
rayon = "1.8.0"
range-ext = "0.3.0"
itertools = "0.12.0"
